#+TITLE: Octave tutorial
* Basic operations
[570] $ octave
GNU Octave, version 3.8.2
Copyright (C) 2014 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin13.4.0".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

** Arithmetic operations
octave:1> 5+6
ans =  11
octave:2> 12-21
ans = -9
octave:3> 1/3
ans =  0.33333
octave:4> 2^8
ans =  256
** Comparisons
octave:5> 2 == 3
ans = 0
octave:6> 2 == 2
ans =  1
octave:7> 2 != 2
ans = 0
octave:8> 2 != 3
ans =  1
octave:9> 2 ~= 3
ans =  1
octave:10> 2 ~= 2
ans = 0
octave:11> # it seems like my version of octave supports "!=" syntax
** Boolean operations
*** AND
#+BEGIN_SRC octave
octave:11> 1 && 1
ans =  1
octave:12> 1 && 0 # AND
ans = 0
octave:13> (2 ~= 2) && (2~=3) # AND
ans = 0
#+END_SRC
*** OR
#+BEGIN_SRC octave
octave:14> (2 ~= 2) || (2~=3) # OR
ans =  1
octave:15> 1 || 0
ans =  1
octave:16> 0 || 0
ans = 0
#+END_SRC
*** XOR
#+BEGIN_SRC octave
octave:17> xor(1,0)
ans =  1
octave:18> xor(1,1)
ans = 0
octave:19> xor(0,0)
ans = 0
#+END_SRC

** Changing Octave prompt
Unicode symbols work too (tested on osx with iterm).
#+BEGIN_SRC octave
octave:1> PS1("☂  ");
☂  
#+END_SRC

** Variables
#+BEGIN_SRC octave
☂  a = 3
a =  3
☂  a = 3; % Semicolumn supresses output
☂
☂  b = "hi";
☂  c = (3>=1);
☂  c
c =  1
☂  ~c
ans = 0
☂  !c
ans = 0
☂
☂  a=pi
a =  3.1416
☂  disp(a)
 3.1416
☂  disp(sprintf("2 decimals: %0.2f", a))
2 decimals: 3.14
☂  disp(sprintf("5 decimals: %0.5f", a))
5 decimals: 3.14159
☂  a
a =  3.1416
☂  format long
☂  a
a =  3.14159265358979
☂  format short
☂  a
a =  3.1416
#+END_SRC

** Values
